[package]
name = "gh-pr-commenter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.17"
tokio = { version = "1", features = ["full"] }
regex = "1"
