[package]
name = "gh-changed-files"
version = "0.1.0"
edition = "2021"

[dependencies]
octocrab = { version = "0.17", features = ["rustls"] }
tokio = { version = "1", features = ["full"] }
regex = "1"
clap = { version = "4.0.19", features = ["derive"] }
serde_json = "1"
